-- =========================================================
-- SEED DATA (PRODUCTION)
-- =========================================================

-- VIRGIN APP POLICY:
-- This application must start completely blank.
-- No real data, no categories, no accounts, and no transactions from the original Excel files are seeded here.
-- All data must be generated by the user through the Onboarding flow or manual insertion.

-- If you need a demo environment for development, create a separate `seed.demo.sql` file.
